### ISSUE TITLE
[feature request] link to media files

### ISSUE THREAD

**Issue by despecial** [gillesgoetsch/acf-smart-button#14]
As the title says, would be great if the smart button plugin could choose between pages/posts and files for internal linking 👍

**Comment by daviddarke** [comment]
You can select which post types are available through the admin as per this pull request: https://github.com/gillesgoetsch/acf-smart-button/pull/13 . So like the example you can select posts, pages and media files. Then sort some logic in your view to adapt the link as required. That make sense?

**Comment by despecial** [comment]
Ah, that's perfect or let's say "smart" 👍 
Wasn't so clear from the readme. Thanks for the headsup.

**Comment by gillesgoetsch** [comment]
Thanks @daviddarke for your support.
