### ISSUE TITLE
Packagist

### ISSUE THREAD

**Issue by patrickgalbraith** [gillesgoetsch/acf-smart-button#16]
Hi love the plugin.

I noticed you have added a `composer.json` file but I was just wondering if you have submitted it to packagist yet (https://packagist.org/) since I can't seem to install it through composer.

**Comment by gillesgoetsch** [comment]
Hi @patrickgalbraith 
Indeed it wasn't submitted yet.Here you go:
https://packagist.org/packages/gillesgoetsch/acf-smart-button

Anything missing?

**Comment by patrickgalbraith** [comment]
Awesome thanks for that looks fine.
