### ISSUE TITLE
Plugin Version

### ISSUE THREAD

**Issue by asadowski10** [gillesgoetsch/acf-smart-button#21]
Hi,

Thanks for your plugin !
You do not update your version number during merges in master. Would it be possible to set up a versionning SEM system?

Best,

**Comment by gillesgoetsch** [comment]
There is currently only one branch: master.
Versioning is added with the releases.

What are you're ideas / steps to go?

**Comment by asadowski10** [comment]
Hello @gillesgoetsch 

Thanks for your answer.
Is-it possible for you to update the plugin version : https://github.com/gillesgoetsch/acf-smart-button/blob/master/acf-smart-button.php#L6 when you make new releases ?

We can easily see the version of the plugin installed from the back office WordPress

Thanks

**Comment by gillesgoetsch** [comment]
You can see the new Version 44dfe576f9b4bc9d4efa4e63048955303010727f and is added to the latest release
