### ISSUE TITLE
Smart button internal links fields empty when opening post in editor.

### ISSUE THREAD

**Issue by Ben764** [gillesgoetsch/acf-smart-button#23]
When I open a page or post in the editor with one or more smart buttons, I noticed that fields for internal links (post objects) are empty. This doesn't happen for external links. Text fields maintain values for both internal and external links. whenever I edit a page or post with smart buttons and save content, smart buttons on this page or post dissappear, because of the empty fields for internal links. Other  act-smart-button is version 1.0.0, ACF is version 5.6.5, Wordpress 4.8.3 and PHP 7.0.

Edit: Empty fields for internal link only occur when a custom post type post is selected in the link field. It doesn't happen for posts or pages.

**Comment by adamriggs** [comment]
I am also having this issue.

**Comment by Ben764** [comment]
Latest version (1.0.1) has a fix for this issue. I downloaded master, which is version 1.0.0. Issue was gone when I downloaded and installed latest (which is 1.0.1).

Version number on line 6 is still on 1.0.0 for file:
https://github.com/gillesgoetsch/acf-smart-button/blob/1.0.1/acf-smart-button.php

**Comment by gillesgoetsch** [comment]
So this is fixed in 1.0.1 according to @Ben764 testing. If not please reopen.
