### ISSUE TITLE
Including in theme

### ISSUE THREAD

**Issue by Tusko** [gillesgoetsch/acf-smart-button#25]
hey!
When I've added plugin to theme [$dir](https://github.com/gillesgoetsch/acf-smart-button/blob/master/acf-smart-button-v5.php#L222) path is going to plugins directory :(

So, my solution is 
`
        $dir = str_replace(get_home_path() ,'/', dirname(__FILE__));
`

Can you check it?

**Comment by gillesgoetsch** [comment]
Hi

The Plugin is meant to be used as a plugin.
If you want to include it in the theme dir, the changes to made seem to to the trick.

However this should not affect the plugin source-code to handle such scenarios.

If it should, let me know.
Thanks
