### ISSUE TITLE
Do not return if not set

### ISSUE THREAD

**Issue by gillesgoetsch** [gillesgoetsch/acf-smart-button#4]
Currently returns same page as url attribute. Should return false to allow correct casing of button

**Comment by cyberwani** [comment]
@gillesgoetsch I send a pullrequest for this issue. Check and merge the change.

**Comment by gillesgoetsch** [comment]
Thanks for your contribution @cyberwani . I've merged your pull request and cleaned it up a bit. Worth to mention is: returning boolean false instead of an empty array to be always clear when checking if the button is set.

**Comment by gillesgoetsch** [comment]
Fixed
