### ISSUE TITLE
Request: Adding the fancy checkbox as a true/false ACF field?

### ISSUE THREAD

**Issue by BoweFrankema** [gillesgoetsch/acf-smart-button#8]
Hi Gilles,

I stumbled upon your plugin by chance and saw how you implemented a nice animated checkbox into your field. Is there any way that could be turned into a new ACF field that can be used instead of the True/False field in ACF? I'd love to see something like that, but haven't been able to make that work at all (probably of my lack of JS skills :-).

**Comment by gillesgoetsch** [comment]
Thanks for you input @BoweFrankema .

I keep your request in mind. This plugin here is explicitly targeted at the button functionality, so this isn't a real issue. Although this should be an easy one, feel free to adapt ;-).
