### ISSUE TITLE
Internal field not rendering when conditional 

### ISSUE THREAD

**Issue by daviddarke** [gillesgoetsch/acf-smart-button#9]
The internal field doesn't seem to render when it's set to conditional:
![vid](https://cloud.githubusercontent.com/assets/1636310/13354490/405411d0-dc93-11e5-8760-8c182daa5c29.gif)

![screen shot 2016-02-26 at 14 14 55](https://cloud.githubusercontent.com/assets/1636310/13354505/5411d84c-dc93-11e5-9a4a-062d3a31266d.png)

**Comment by gillesgoetsch** [comment]
Thanks @daviddarke . May I ask for your WP and ACF5 version?
I can't reproduce this issue with the latests versions. Any js error, other possible conflicts? If you help me reproduce the behavior I might be able to help you further.

**Comment by daviddarke** [comment]
WP 4.4.2 -  with Twenty Fifteen selected
ACF Pro 5.3.5

No JS errors.

Here is an example ACF group export - http://pastebin.com/jiygk8Rz

**Comment by daviddarke** [comment]
Any thoughts?

**Comment by gillesgoetsch** [comment]
Here you go. Thanks for detecting that issue.

**Comment by daviddarke** [comment]
NICEEEEEEEEEEEEEEE! I'll have a test asap
